import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NzCodeEditorComponent, NzCodeEditorModule } from 'ng-zorro-antd/code-editor';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrl: './welcome.component.scss',
  standalone: true,
  imports: [ FormsModule]
})
export class WelcomeComponent {
  constructor() {}

  sqlcode = `

IF DB_ID('INVENTORYDB') IS NOT NULL
BEGIN
    ALTER DATABASE INVENTORYDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE INVENTORYDB;
END
GO

CREATE DATABASE INVENTORYDB;
GO

USE INVENTORYDB;
GO

CREATE TABLE CATEGORIAS (
    ID          INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE      NVARCHAR(50)  NOT NULL,
    DESCRIPCION NVARCHAR(250)
);
GO

CREATE TABLE PRODUCTOS (
    ID          INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE      NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(500),
    PRECIO      DECIMAL(18,2) NOT NULL,
    STOCK       INT NOT NULL
);
GO

CREATE TABLE PRODUCTO_CATEGORIA (
    ID           INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCTO_ID  INT NOT NULL,
    CATEGORIA_ID INT NOT NULL,
    CONSTRAINT UQ_PRODCAT UNIQUE (PRODUCTO_ID, CATEGORIA_ID),
    CONSTRAINT FK_PRODCAT_PRODUCTO  FOREIGN KEY (PRODUCTO_ID)  REFERENCES PRODUCTOS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_PRODCAT_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS(ID) ON DELETE CASCADE
);
GO

CREATE TABLE TRANSACCIONES (
    ID                INT IDENTITY(1,1) PRIMARY KEY,
    FECHA             DATETIME2(6)  NOT NULL,
    TIPO_TRANSACCION  NVARCHAR(50)  NOT NULL,
    DETALLE           NVARCHAR(MAX)
);
GO

CREATE TABLE TRANSACCION_PRODUCTOS (
    ID              INT IDENTITY(1,1) PRIMARY KEY,
    TRANSACCION_ID  INT NOT NULL,
    PRODUCTO_ID     INT NOT NULL,
    CANTIDAD        INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(18,2) NOT NULL,
    PRECIO_TOTAL    DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_TXPROD_TRANSACCION FOREIGN KEY (TRANSACCION_ID) REFERENCES TRANSACCIONES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TXPROD_PRODUCTO    FOREIGN KEY (PRODUCTO_ID)    REFERENCES PRODUCTOS(ID)     ON DELETE CASCADE
);
GO

INSERT INTO CATEGORIAS (NOMBRE)
VALUES ('Electrónica'), ('Accesorios');
GO

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK) VALUES
('Laptop',  '14-inch 16 GB RAM', 799.99,  50),
('Mouse',   'Ergonómico USB',     19.90, 150),
('Teclado', 'Mecánico',           29.90, 120);
GO

INSERT INTO PRODUCTO_CATEGORIA (PRODUCTO_ID, CATEGORIA_ID) VALUES
(1, 1),
(2, 1),
(2, 2),
(3, 1),
(3, 2);
GO

INSERT INTO TRANSACCIONES (FECHA, TIPO_TRANSACCION, DETALLE)
VALUES (GETDATE(), 'VENTA', 'Venta web #1001');
GO

DECLARE @TxId INT = SCOPE_IDENTITY();

INSERT INTO TRANSACCION_PRODUCTOS
        (TRANSACCION_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNITARIO, PRECIO_TOTAL)
VALUES  (@TxId, 1, 1, 799.99, 799.99),
        (@TxId, 2, 2,  19.90,  39.80);
GO
`
}
