services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "Str0ng_Passw0rd!"
    volumes:
      - sql_data:/var/opt/mssql    
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  sql_data: 
