DROP DATABASE IF EXISTS "INVENTORYDB";
CREATE DATABASE "INVENTORYDB";

DROP TABLE IF EXISTS "TRANSACCION_PRODUCTOS" CASCADE;
DROP TABLE IF EXISTS "TRANSACCIONES"          CASCADE;
DROP TABLE IF EXISTS "PRODUCTOCATEGORIA"      CASCADE;
DROP TABLE IF EXISTS "PRODUCTOS"              CASCADE;
DROP TABLE IF EXISTS "CATEGORIAS"             CASCADE;

CREATE TABLE "CATEGORIAS" (
    "ID"          SERIAL PRIMARY KEY,
    "NOMBRE"      VARCHAR(50)  NOT NULL,
    "DESCRIPCION" VARCHAR(250)
);

CREATE TABLE "PRODUCTOS" (
    "ID"          SERIAL PRIMARY KEY,
    "NOMBRE"      VARCHAR(100) NOT NULL,
    "DESCRIPCION" VARCHAR(500),
    "PRECIO"      NUMERIC(18,2) NOT NULL,
    "STOCK"       INTEGER NOT NULL
);

CREATE TABLE "PRODUCTOCATEGORIA" (
    "ID"           SERIAL PRIMARY KEY,
    "PRODUCTO_ID"  INTEGER NOT NULL,
    "CATEGORIA_ID" INTEGER NOT NULL,
    CONSTRAINT "UQ_PRODCAT" UNIQUE ("PRODUCTO_ID", "CATEGORIA_ID"),
    CONSTRAINT "FK_PRODCAT_PRODUCTO"
        FOREIGN KEY ("PRODUCTO_ID")  REFERENCES "PRODUCTOS"  ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_PRODCAT_CATEGORIA"
        FOREIGN KEY ("CATEGORIA_ID") REFERENCES "CATEGORIAS" ("ID") ON DELETE CASCADE
);

CREATE TABLE "TRANSACCIONES" (
    "ID"               SERIAL PRIMARY KEY,
    "FECHA"            TIMESTAMP WITH TIME ZONE NOT NULL,
    "TIPO_TRANSACCION" VARCHAR(50)            NOT NULL,
    "DETALLE"          TEXT
);

CREATE TABLE "TRANSACCION_PRODUCTOS" (
    "ID"              SERIAL PRIMARY KEY,
    "TRANSACCION_ID"  INTEGER NOT NULL,
    "PRODUCTO_ID"     INTEGER NOT NULL,
    "CANTIDAD"        INTEGER NOT NULL,
    "PRECIO_UNITARIO" NUMERIC(18,2) NOT NULL,
    "PRECIO_TOTAL"    NUMERIC(18,2) NOT NULL,
    CONSTRAINT "FK_TXPROD_TRANSACCION"
        FOREIGN KEY ("TRANSACCION_ID") REFERENCES "TRANSACCIONES" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_TXPROD_PRODUCTO"
        FOREIGN KEY ("PRODUCTO_ID")    REFERENCES "PRODUCTOS"     ("ID") ON DELETE CASCADE
);

INSERT INTO "CATEGORIAS" ("NOMBRE")
VALUES ('Electrónica'), ('Accesorios');

INSERT INTO "PRODUCTOS" ("NOMBRE", "DESCRIPCION", "PRECIO", "STOCK") VALUES
    ('Laptop',  '14-inch 16 GB RAM', 799.99,  50),
    ('Mouse',   'Ergonómico USB',     19.90, 150),
    ('Teclado', 'Mecánico',           29.90, 120);

INSERT INTO "PRODUCTOCATEGORIA" ("PRODUCTO_ID", "CATEGORIA_ID") VALUES
    (1, 1),
    (2, 1),
    (2, 2),
    (3, 1),
    (3, 2);

WITH nueva_tx AS (
    INSERT INTO "TRANSACCIONES" ("FECHA", "TIPO_TRANSACCION", "DETALLE")
    VALUES (NOW(), 'VENTA', 'Venta web #1001')
    RETURNING "ID"
)
INSERT INTO "TRANSACCION_PRODUCTOS"
        ("TRANSACCION_ID", "PRODUCTO_ID", "CANTIDAD",
         "PRECIO_UNITARIO", "PRECIO_TOTAL")
SELECT n."ID", 1, 1, 799.99, 799.99 FROM nueva_tx n
UNION ALL
SELECT n."ID", 2, 2,  19.90,  39.80 FROM nueva_tx n;